name: Test Restaurant App

on:
  - push
  - pull_request

jobs:
  test-components:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test using Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '18.7'
      - name: Install dependencies
        run: yarn install
      - name: Run tests
        env:
          REACT_APP_RESTAURANT_NAME: ${{ secrets.react_app_restaurant_name }}
          REACT_APP_CURRENCY_SYMBOL: ${{ secrets.react_app_currency_symbol }}
          REACT_APP_DELIVERY_PRICE: ${{ secrets.react_app_delivery_price }}
          REACT_APP_ADMIN_MAIL: ${{ secrets.react_app_admin_email }}
          REACT_APP_FIREBASE_API_KEY: ${{ secrets.react_app_firebase_api_key }}
          REACT_APP_FIREBASE_AUTH_DOMAIN: ${{ secrets.react_app_firebase_auth_domain }}
          REACT_APP_FIREBASE_DB_URL: ${{ secrets.react_app_firebase_db_url }}
          REACT_APP_FIREBASE_PROJECT_ID: ${{ secrets.react_app_firebase_project_id }}
          REACT_APP_FIREBASE_STORAGE_BUCKET: ${{ secrets.react_app_firebase_storage_bucket }}
          REACT_APP_FIREBASE_MESSAGING_ID: ${{ secrets.react_app_messaging_id }}
          REACT_APP_FIREBASE_APP_ID: ${{ secrets.react_app_firebase_app_id }}
        run: yarn test